/** Real Web composition: keyboard routing, inline editing, and localized system feedback. */
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { chromium, type Browser } from 'playwright'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { openSettings } from './support.ts'
import { captureStableAria, compareOrRefreshGolden, launchWebScaffold, watchConsole, webSnapshotMode, type WebScaffold } from './scaffold.ts'

const expected = fileURLToPath(new URL('./expected/shortcuts', import.meta.url))
const mode = webSnapshotMode()

describe('web e2e: shortcut reference', () => {
  let scaffold: WebScaffold
  let browser: Browser
  beforeAll(async () => {
    scaffold = await launchWebScaffold({ developerTools: false })
    browser = await chromium.launch()
  }, 120_000)
  afterAll(async () => { await browser?.close(); await scaffold?.close() })

  it.each([
    { locale: 'zh-CN', platform: 'MacIntel', title: '快捷键', settings: '设置', view: '编辑快捷键', search: '搜索快捷键', key: 'Meta' },
    { locale: 'en-US', platform: 'Win32', title: 'Keyboard shortcuts', settings: 'Settings', view: 'Edit shortcuts', search: 'Search shortcuts', key: 'Control' },
  ])('opens, searches, and restores nested focus in $locale', async ({ locale, platform, title, settings, view, search, key }) => {
    const referenceKey = platform === 'Win32' ? 'Control+Slash' : 'Meta+Slash'
    const context = await browser.newContext({ locale, colorScheme: 'light', viewport: { width: 1440, height: 1000 } })
    try {
      // Branch coverage for device labels; native Windows input is separately verified on Windows.
      await context.addInitScript((value) => { Object.defineProperty(navigator, 'platform', { value }) }, platform)
      const page = await context.newPage()
      const console = watchConsole(page)
      await page.goto(scaffold.authenticatedUrl, { waitUntil: 'load' })
      await page.waitForSelector('[class*="frame"]', { timeout: 30_000 })
      const trigger = page.getByRole('button', { name: settings, exact: true })
      expect(await trigger.getAttribute('aria-keyshortcuts')).toBe(`${key}+,`)
      const settingsHint = `${settings} ${key === 'Meta' ? '⌘ ,' : 'Ctrl + ,'}`
      await trigger.hover()
      await page.getByRole('tooltip', { name: settingsHint, exact: true }).waitFor()
      await trigger.click()
      await page.getByRole('button', { name: view, exact: true }).click()
      const dialog = page.getByRole('dialog', { name: title, exact: true })
      await dialog.waitFor()
      const referenceNode = await dialog.elementHandle()
      expect(await page.getByRole('dialog').count()).toBe(2)
      expect(await dialog.locator('footer').count()).toBe(1)
      const resetAll = dialog.getByRole('button', { name: locale === 'zh-CN' ? '恢复全部默认' : 'Restore all defaults', exact: true })
      expect(await resetAll.isDisabled()).toBe(true)
      expect(await dialog.boundingBox()).toMatchObject({ width: 480, height: 600 })
      expect(await dialog.getByRole('search').boundingBox()).toMatchObject({ width: 440, height: 36 })
      const rows = dialog.getByRole('listitem')
      const stopRow = dialog.getByRole('region', { name: locale === 'zh-CN' ? '消息输入' : 'Message input', exact: true })
        .getByRole('listitem').last()
      await stopRow.getByText(locale === 'zh-CN' ? '停止生成' : 'Stop generating', { exact: true }).waitFor()
      const stopButtons = stopRow.getByRole('button')
      expect(await stopButtons.count()).toBe(0)
      expect(new Set(await rows.evaluateAll(items => items.map(row => row.getBoundingClientRect().height))))
        .toEqual(new Set([42]))
      expect(await rows.evaluateAll(items => items.every(row => row.getBoundingClientRect().height >= 42
        && row.scrollWidth <= row.clientWidth))).toBe(true)
      const searchInput = page.getByRole('searchbox', { name: search })
      expect(await searchInput.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await searchInput.evaluate(element => ({
        outline: getComputedStyle(element).outlineStyle, shadow: getComputedStyle(element).boxShadow,
      }))).toEqual({ outline: 'none', shadow: 'none' })
      const searchSurfaceStyle = () => dialog.getByRole('search').evaluate((element) => {
        const style = getComputedStyle(element)
        return { border: style.borderColor, outline: style.outlineStyle, shadow: style.boxShadow }
      })
      const focusedSearchSurface = await searchSurfaceStyle()
      expect(focusedSearchSurface).toMatchObject({ outline: 'none', shadow: 'none' })
      const dialogShadow = await dialog.evaluate(element => getComputedStyle(element).boxShadow)
      await compareOrRefreshGolden(join(expected, `${locale}.expected.md`),
        await captureStableAria(page, '[data-shortcut-modal="shortcuts"]', scaffold.workspaceCwd), mode)
      const fixedBackground = await stopRow.evaluate(element => getComputedStyle(element).backgroundColor)
      await stopRow.hover()
      expect(await stopRow.evaluate(element => getComputedStyle(element).backgroundColor)).toBe(fixedBackground)
      const editLabel = locale === 'zh-CN' ? '修改展开／收起左侧栏快捷键' : 'Edit shortcut for Toggle left sidebar'
      const row = dialog.getByRole('listitem').filter({ has: page.getByRole('button', { name: editLabel, exact: true }) })
      const editButton = page.getByRole('button', { name: editLabel, exact: true })
      expect(await row.locator('[class*="rowActions"]').evaluate(element => getComputedStyle(element).opacity)).toBe('0')
      const boundRow = dialog.getByRole('listitem').filter({ has: page.getByText(
        locale === 'zh-CN' ? '快捷键速查' : 'Open keyboard shortcuts', { exact: true },
      ) })
      const badge = boundRow.getByRole('button', { name: locale === 'zh-CN' ? '修改快捷键速查快捷键' : 'Edit shortcut for Open keyboard shortcuts', exact: true })
      const restingColor = await boundRow.evaluate(element => getComputedStyle(element).backgroundColor)
      await badge.hover({ position: { x: 12, y: 12 } })
      expect(await boundRow.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe(restingColor)
      expect(await boundRow.evaluate(element => getComputedStyle(element).borderRadius)).toBe('12px')
      expect(await badge.boundingBox()).toEqual(await boundRow.boundingBox())
      await badge.click()
      await boundRow.getByRole('group').waitFor()
      expect(await searchSurfaceStyle()).toEqual(focusedSearchSurface)
      expect(new Set(await rows.evaluateAll(items => items.map(row => row.getBoundingClientRect().height))))
        .toEqual(new Set([42]))
      expect(await boundRow.getByRole('button', { name: locale === 'zh-CN' ? '移除' : 'Remove', exact: true }).count()).toBe(1)
      await page.keyboard.press('Escape')
      await boundRow.getByRole('group').waitFor({ state: 'hidden' })
      await dialog.getByRole('heading', { name: title, exact: true }).hover()
      const boundActionsOpacity = () => boundRow.locator('[class*="rowActions"]').evaluate(element => getComputedStyle(element).opacity)
      expect(await boundActionsOpacity()).toBe('0')
      expect(await dialog.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await dialog.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await dialog.evaluate(element => getComputedStyle(element).boxShadow)).toBe(dialogShadow)
      await page.keyboard.press('Shift+Tab')
      expect(await dialog.getByRole('button', { disabled: false }).last().evaluate(element => element === document.activeElement)).toBe(true)
      expect(await dialog.getByRole('button', { disabled: false }).last().evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe('none')
      await badge.click()
      await boundRow.getByRole('button', { name: locale === 'zh-CN' ? '恢复默认' : 'Restore default', exact: true }).click()
      await boundRow.getByRole('group').waitFor({ state: 'hidden' })
      await dialog.getByRole('heading', { name: title, exact: true }).hover()
      expect(await boundActionsOpacity()).toBe('0')
      await row.hover()
      expect(await row.locator('[class*="rowActions"]').evaluate(element => getComputedStyle(element).opacity)).toBe('1')
      expect(await row.getByRole('button').count()).toBe(1)
      await editButton.click()
      const inline = dialog.getByRole('group', { name: locale === 'zh-CN' ? '展开／收起左侧栏' : 'Toggle left sidebar', exact: true })
      const recorder = inline.getByRole('button', { name: locale === 'zh-CN' ? '按下快捷键' : 'Press a shortcut', exact: true })
      expect(await inline.getByRole('button', { name: locale === 'zh-CN' ? '移除' : 'Remove', exact: true }).count()).toBe(1)
      expect(await page.getByRole('dialog').count()).toBe(2)
      expect(await recorder.evaluate(element => ({
        color: getComputedStyle(element).color, border: getComputedStyle(element).borderColor,
      })))
        .toEqual({ color: 'rgb(97, 102, 107)', border: 'rgba(0, 0, 0, 0.16)' })
      expect(await recorder.evaluate(element => ({
        focused: element === document.activeElement,
        outline: getComputedStyle(element).outlineStyle, shadow: getComputedStyle(element).boxShadow,
      }))).toEqual({ focused: true, outline: 'none', shadow: 'none' })
      await compareOrRefreshGolden(join(expected, `${locale}-inline.expected.md`),
        await captureStableAria(page, '[data-shortcut-modal="shortcut-edit"]', scaffold.workspaceCwd), mode)
      await page.keyboard.press(referenceKey)
      const errorToast = page.getByRole('alert').filter({ hasText: locale === 'zh-CN' ? '已被「快捷键速查」占用' : 'Already used by “Open keyboard shortcuts”' })
      await errorToast.waitFor()
      expect(await errorToast.evaluate(element => ({
        background: getComputedStyle(element).backgroundColor, color: getComputedStyle(element).color,
      })))
        .toEqual({ background: 'rgb(53, 54, 56)', color: 'rgb(255, 255, 255)' })
      expect(await errorToast.evaluate(element => element.closest('[role="dialog"]') === null)).toBe(true)
      expect(await recorder.evaluate(element => ({
        color: getComputedStyle(element).borderColor, width: getComputedStyle(element).borderWidth,
      })))
        .toEqual({ color: 'rgb(236, 19, 19)', width: '1px' })
      await compareOrRefreshGolden(join(expected, `${locale}-conflict.expected.md`), await errorToast.ariaSnapshot(), mode)
      await page.keyboard.press('i')
      await page.getByRole('alert').filter({ hasText: locale === 'zh-CN'
        ? '请同时按下 Command、Ctrl 或 Alt 修饰键。' : 'Include Command, Ctrl, or Alt in the combination.' }).waitFor()
      await page.keyboard.press(`${key}+Shift+.`)
      await inline.waitFor({ state: 'hidden' })
      expect(await dialog.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await dialog.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await dialog.evaluate(element => getComputedStyle(element).boxShadow)).toBe(dialogShadow)
      expect(await editButton.evaluate(element => element.matches(':focus-visible'))).toBe(false)
      await dialog.getByRole('heading', { name: title, exact: true }).hover()
      expect(await row.locator('[class*="rowActions"]').evaluate(element => getComputedStyle(element).opacity)).toBe('0')
      await page.keyboard.press('Shift+Tab')
      expect(await resetAll.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await resetAll.evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe('none')
      const successToast = page.getByRole('alert').filter({ hasText: locale === 'zh-CN' ? '已修改' : 'Modified' })
      await successToast.waitFor()
      await compareOrRefreshGolden(join(expected, `${locale}-saved.expected.md`), await successToast.ariaSnapshot(), mode)
      await page.emulateMedia({ colorScheme: 'dark' })
      await expect.poll(() => successToast.evaluate(element => ({
        background: getComputedStyle(element).backgroundColor, color: getComputedStyle(element).color,
      }))).toEqual({ background: 'rgb(67, 69, 74)', color: 'rgb(255, 255, 255)' })
      await page.emulateMedia({ colorScheme: 'light' })
      await expect.poll(() => successToast.evaluate(element => getComputedStyle(element).backgroundColor)).toBe('rgb(53, 54, 56)')
      await editButton.click()
      await inline.getByRole('button', { name: locale === 'zh-CN' ? '移除' : 'Remove', exact: true }).click()
      await inline.waitFor({ state: 'hidden' })
      const unbound = row.getByText(locale === 'zh-CN' ? '暂无快捷键' : 'No shortcut', { exact: true })
      await unbound.waitFor()
      expect(await unbound.evaluate(element => getComputedStyle(element).color)).toBe('rgb(129, 133, 140)')
      expect(await row.getByRole('button').count()).toBe(1)
      await editButton.click({ position: { x: 12, y: 12 } })
      await inline.waitFor()
      expect(await inline.getByRole('button', { name: locale === 'zh-CN' ? '移除' : 'Remove', exact: true }).count()).toBe(0)
      await page.keyboard.press('Escape')
      await inline.waitFor({ state: 'hidden' })
      expect(await dialog.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await dialog.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await dialog.evaluate(element => getComputedStyle(element).boxShadow)).toBe(dialogShadow)
      await dialog.getByRole('heading', { name: title, exact: true }).hover()
      expect(await row.getByRole('button').count()).toBe(1)
      expect(await page.getByRole('dialog').count()).toBe(2)
      for (const query of ['abc', 'sendEnter']) {
        await page.getByRole('searchbox').fill(query)
        expect(await dialog.getByRole('listitem').count()).toBe(0)
        expect(await dialog.getByRole('status').textContent()).toBe(locale === 'zh-CN' ? '没有匹配的快捷键' : 'No matching shortcuts')
        if (query === 'abc') await compareOrRefreshGolden(join(expected, `${locale}-empty.expected.md`),
          await captureStableAria(page, '[data-shortcut-modal="shortcuts"]', scaffold.workspaceCwd), mode)
      }
      for (const query of [locale === 'zh-CN' ? '左侧栏' : 'toggle left', 'tgllft', 'toggle left sidebar']) {
        await page.getByRole('searchbox').fill(query)
        expect(await dialog.getByRole('listitem').count()).toBe(1)
        expect(await dialog.getByRole('listitem').textContent()).toContain(locale === 'zh-CN' ? '展开／收起左侧栏' : 'Toggle left sidebar')
      }
      await page.keyboard.press(`${key}+Comma`)
      expect(await referenceNode!.evaluate(element => element.isConnected)).toBe(true)
      expect(await page.getByRole('dialog').count()).toBe(2)
      expect(await page.getByRole('searchbox').inputValue()).toBe('toggle left sidebar')
      expect(await searchInput.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await searchSurfaceStyle()).toEqual(focusedSearchSurface)
      await page.keyboard.press(referenceKey)
      await dialog.waitFor({ state: 'hidden' })
      expect(await page.getByRole('dialog').count()).toBe(1)
      expect(await page.getByRole('button', { name: view, exact: true }).evaluate(element => element === document.activeElement)).toBe(true)
      expect(await page.getByRole('button', { name: view, exact: true }).getAttribute('data-dsh-automatic-focus')).toBe('')
      expect(await page.getByRole('button', { name: view, exact: true }).evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      await page.keyboard.press(`${key}+Comma`)
      await page.getByRole('dialog', { name: settings, exact: true }).waitFor({ state: 'hidden' })
      expect(await page.getByRole('dialog').count()).toBe(0)
      expect(await trigger.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await trigger.getAttribute('data-dsh-automatic-focus')).toBe('')
      expect(await trigger.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      await page.keyboard.press(referenceKey)
      await dialog.waitFor()
      await page.keyboard.press(`${key}+Comma`)
      expect(await page.getByRole('dialog', { name: settings, exact: true }).isVisible()).toBe(false)
      expect(await page.getByRole('dialog').count()).toBe(1)
      expect(await searchInput.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await searchInput.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      await page.keyboard.press(`${key}+/`)
      await dialog.waitFor({ state: 'hidden' })
      expect(await page.getByRole('dialog').count()).toBe(0)
      await page.keyboard.press(referenceKey)
      await dialog.waitFor()
      expect(await page.getByRole('dialog').count()).toBe(1)
      expect(await page.getByRole('searchbox').inputValue()).toBe('')
      await page.setViewportSize({ width: 420, height: 500 })
      const compactBounds = (await dialog.boundingBox())!
      expect(compactBounds.x).toBeGreaterThanOrEqual(24)
      expect(compactBounds.x + compactBounds.width).toBeLessThanOrEqual(396)
      expect(compactBounds.y + compactBounds.height).toBeLessThanOrEqual(476)
      await dialog.getByRole('region').last().scrollIntoViewIfNeeded()
      expect(await dialog.getByRole('heading', { name: title }).isVisible()).toBe(true)
      await page.keyboard.press('Escape')
      // Observe preventDefault without invoking destructive browser defaults in the test runner.
      expect(await page.evaluate(modifier => ['KeyN', 'KeyP', 'KeyO', 'KeyR', 'KeyW', 'KeyB'].map((code) => {
        const event = new KeyboardEvent('keydown', { code, ctrlKey: modifier === 'Control', metaKey: modifier === 'Meta', bubbles: true, cancelable: true })
        document.body.dispatchEvent(event)
        return event.defaultPrevented
      }), key)).toEqual(Array<boolean>(6).fill(false))
      await page.setViewportSize({ width: 1440, height: 1000 })
      await openSettings(page, locale === 'zh-CN' ? 'zh' : 'en')
      const viewButton = page.getByRole('button', { name: view, exact: true })
      const viewHint = `${locale === 'zh-CN' ? '全局唤起查看' : 'Open from anywhere'} ${key === 'Meta' ? '⌘ /' : 'Ctrl + /'}`
      await viewButton.hover()
      expect(await page.getByRole('tooltip').getAttribute('aria-label')).toBe(viewHint)
      await viewButton.click()
      await badge.click()
      await boundRow.getByRole('button', { name: locale === 'zh-CN' ? '移除' : 'Remove', exact: true }).click()
      await boundRow.getByRole('group').waitFor({ state: 'hidden' })
      await boundRow.getByText(locale === 'zh-CN' ? '暂无快捷键' : 'No shortcut', { exact: true }).waitFor()
      await page.keyboard.press('Escape')
      await dialog.waitFor({ state: 'hidden' })
      expect(await viewButton.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await viewButton.getAttribute('data-dsh-automatic-focus')).toBe('')
      expect(await viewButton.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      await viewButton.hover()
      expect(await page.getByRole('tooltip').count()).toBe(0)
      expect(await viewButton.getAttribute('aria-keyshortcuts')).toBeNull()
      await viewButton.click()
      await badge.click()
      await boundRow.getByRole('button', { name: locale === 'zh-CN' ? '恢复默认' : 'Restore default', exact: true }).click()
      await boundRow.getByRole('group').waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      await dialog.waitFor({ state: 'hidden' })
      await viewButton.hover()
      expect(await page.getByRole('tooltip').getAttribute('aria-label')).toBe(viewHint)
      await viewButton.click()
      await page.getByRole('searchbox').fill('abc')
      expect(await dialog.getByRole('listitem').count()).toBe(0)
      expect(await dialog.locator('footer').textContent()).toContain(locale === 'zh-CN' ? '1 项已自定义' : '1 customized')
      await resetAll.click()
      const confirm = page.getByRole('dialog', { name: locale === 'zh-CN' ? '恢复全部默认快捷键？' : 'Restore all default shortcuts?', exact: true })
      const cancel = confirm.getByRole('button', { name: locale === 'zh-CN' ? '取消' : 'Cancel', exact: true })
      expect(await cancel.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await cancel.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      await compareOrRefreshGolden(join(expected, `${locale}-reset-confirm.expected.md`), await confirm.ariaSnapshot(), mode)
      await cancel.click()
      expect(await resetAll.evaluate(element => element === document.activeElement)).toBe(true)
      expect(await resetAll.getAttribute('data-dsh-automatic-focus')).toBe('')
      expect(await resetAll.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await dialog.locator('footer').textContent()).toContain(locale === 'zh-CN' ? '1 项已自定义' : '1 customized')
      await resetAll.click()
      await confirm.getByRole('button', { name: locale === 'zh-CN' ? '恢复默认' : 'Restore default', exact: true }).click()
      await confirm.waitFor({ state: 'hidden' })
      expect(await resetAll.isDisabled()).toBe(true)
      expect(await dialog.locator('footer').textContent()).toBe(locale === 'zh-CN' ? '恢复全部默认' : 'Restore all defaults')
      expect(await page.getByRole('searchbox').evaluate(element => element === document.activeElement)).toBe(true)
      expect(await searchInput.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
      expect(await searchSurfaceStyle()).toEqual(focusedSearchSurface)
      await page.keyboard.press('Escape')
      await page.keyboard.press('Escape')
      await page.keyboard.press(referenceKey)
      const settingsCommand = locale === 'zh-CN' ? '打开设置' : 'Open settings'
      await dialog.getByRole('button', { name: locale === 'zh-CN' ? `修改${settingsCommand}快捷键` : `Edit shortcut for ${settingsCommand}`, exact: true }).click()
      await page.keyboard.press(`${key}+Shift+Comma`)
      await dialog.getByRole('group').waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      expect(await trigger.getAttribute('aria-keyshortcuts')).toBe(key === 'Meta' ? 'Shift+Meta+,' : 'Control+Shift+,')
      await trigger.hover()
      await page.getByRole('tooltip', { name: `${settings} ${key === 'Meta' ? '⇧ ⌘ ,' : 'Ctrl + Shift + ,'}`, exact: true }).waitFor()
      await trigger.click()
      await page.keyboard.press('Escape')
      expect(await trigger.evaluate(element => element === document.activeElement)).toBe(true)
      await page.keyboard.press(referenceKey)
      await dialog.getByRole('button', { name: locale === 'zh-CN' ? `修改${settingsCommand}快捷键` : `Edit shortcut for ${settingsCommand}`, exact: true }).click()
      await dialog.getByRole('button', { name: locale === 'zh-CN' ? '恢复默认' : 'Restore default', exact: true }).click()
      await dialog.getByRole('group').waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      expect(await trigger.getAttribute('aria-keyshortcuts')).toBe(`${key}+,`)
      await trigger.hover()
      await page.getByRole('tooltip', { name: settingsHint, exact: true }).waitFor()
      const sidebar = page.getByRole('button', { name: locale === 'zh-CN' ? '收起侧边栏' : 'Collapse sidebar', exact: true })
      expect(await sidebar.getAttribute('aria-keyshortcuts')).toBe(key === 'Meta' ? 'Alt+Meta+B' : 'Control+Alt+B')
      await page.reload({ waitUntil: 'load' })
      await sidebar.waitFor()
      expect(await sidebar.getAttribute('aria-keyshortcuts')).toBe(key === 'Meta' ? 'Alt+Meta+B' : 'Control+Alt+B')
      expect(console.pageErrors).toEqual([])
      expect(console.warnings).toEqual([])
    } finally { await context.close() }
  })

  it.each([
    { platform: 'Win32', primary: 'Control', keys: 'Ctrl + Alt + N' },
    { platform: 'MacIntel', primary: 'Meta', keys: '⌥ ⇧ ⌘ F12' },
  ])('shows the shortcut inside New Session on hover and keyboard focus at wide and narrow widths on $platform', async ({ platform, primary, keys }) => {
    const context = await browser.newContext({ locale: 'en-US', viewport: { width: 1440, height: 1000 } })
    try {
      await context.addInitScript((value) => { Object.defineProperty(navigator, 'platform', { value }) }, platform)
      const page = await context.newPage()
      await page.goto(scaffold.authenticatedUrl)
      const newSession = page.getByRole('button', { name: 'New session', exact: true }).filter({ hasText: 'New Session' })
      await newSession.waitFor()
      if (platform === 'MacIntel') await page.evaluate(() => { document.documentElement.dataset.platform = 'darwin' })
      await page.keyboard.press(`${primary}+/`)
      await page.getByRole('button', { name: 'Edit shortcut for New Session', exact: true }).click()
      await page.keyboard.press(platform === 'Win32' ? 'Control+Alt+N' : 'Meta+Alt+Shift+F12')
      await page.getByRole('group', { name: 'New Session', exact: true }).waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      for (const colorScheme of ['light', 'dark'] as const) {
        await page.emulateMedia({ colorScheme })
        for (const width of [420, 264]) {
          const handle = (await page.locator('[data-side="sidebar"]').boundingBox())!
          await page.mouse.move(handle.x + handle.width / 2, 240)
          await page.mouse.down()
          await page.mouse.move(width, 240, { steps: 10 })
          await page.mouse.up()
          await expect.poll(() => newSession.locator('kbd').allTextContents()).toEqual(keys.split(' '))
          const centerOffset = () => newSession.evaluate((element) => {
            const button = element.getBoundingClientRect()
            const content = element.querySelector('[class*="newSessionContent"]')!.getBoundingClientRect()
            return Math.abs(button.x + button.width / 2 - content.x - content.width / 2)
          })
          expect(await centerOffset()).toBeLessThan(1)
          const hintStyle = () => newSession.locator('[class*="newSessionShortcut"]').evaluate(element => ({
            opacity: getComputedStyle(element).opacity, mask: getComputedStyle(element.previousElementSibling!).maskImage,
          }))
          expect(await hintStyle()).toEqual({ opacity: '0', mask: 'none' })
          await newSession.hover()
          expect(await centerOffset()).toBeLessThan(1)
          const mask = await newSession.locator('[class*="newSessionLabelMask"]').boundingBox()
          const hint = await newSession.locator('[class*="newSessionShortcut"]').boundingBox()
          expect(mask!.x + mask!.width).toBeLessThanOrEqual(hint!.x + 1)
          expect((await hintStyle()).opacity).toBe('1')
          expect((await hintStyle()).mask).toContain('linear-gradient')
          await newSession.screenshot({ path: fileURLToPath(new URL(`../../../.artifacts/new-session-${process.pid}-${platform}-${colorScheme}-${width}.png`, import.meta.url)) })
          expect(await page.getByRole('tooltip').count()).toBe(0)
          await page.mouse.move(700, 100)
          expect(await hintStyle()).toEqual({ opacity: '0', mask: 'none' })
          await newSession.focus()
          await page.keyboard.press('Shift+Tab')
          await page.keyboard.press('Tab')
          expect(await newSession.evaluate(element => element.matches(':focus-visible'))).toBe(true)
          expect((await hintStyle()).opacity).toBe('1')
          expect(await page.getByRole('tooltip').count()).toBe(0)
          await newSession.evaluate((element) => { element.blur() })
        }
      }
    } finally { await context.close() }
  })

  it.each([
    { platform: 'Win32', modifier: 'Control', defaultBinding: 'Control+Alt+B' },
    { platform: 'MacIntel', modifier: 'Meta', defaultBinding: 'Alt+Meta+B' },
    { platform: 'Linux x86_64', modifier: 'Control', defaultBinding: null },
  ])('records, rejects conflicts, persists across reload, and synchronizes stale drafts between tabs on $platform', async ({ platform, modifier, defaultBinding }) => {
    const context = await browser.newContext({ locale: 'en-US', viewport: { width: 1440, height: 1000 } })
    try {
      await context.addInitScript((value) => { Object.defineProperty(navigator, 'platform', { value }) }, platform)
      const page = await context.newPage()
      await page.goto(scaffold.authenticatedUrl, { waitUntil: 'load' })
      await page.getByRole('button', { name: 'Settings', exact: true }).waitFor()
      const referenceKey = `${modifier}+Slash`
      const open = async () => {
        await page.keyboard.press(referenceKey)
        await page.getByRole('dialog', { name: 'Keyboard shortcuts', exact: true }).waitFor()
      }
      await open()
      await page.getByRole('button', { name: 'Edit shortcut for Toggle left sidebar', exact: true }).click()
      const editor = page.getByRole('group', { name: 'Toggle left sidebar', exact: true })
      await editor.getByRole('button', { name: 'Press a shortcut', exact: true }).focus()
      await page.keyboard.press(referenceKey)
      await page.getByRole('alert').filter({ hasText: 'Already used by “Open keyboard shortcuts”' }).waitFor()
      expect(await editor.getByRole('button', { name: 'Press a shortcut', exact: true }).getAttribute('aria-invalid')).toBe('true')
      await page.keyboard.press(`${modifier}+Shift+.`)
      await editor.waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      const sidebarKey = `${modifier}+Shift+.`
      expect(await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).getAttribute('aria-keyshortcuts'))
        .toBe(modifier === 'Meta' ? 'Shift+Meta+.' : 'Control+Shift+.')
      await page.keyboard.press(sidebarKey)
      await page.getByRole('button', { name: 'Open sidebar', exact: true }).waitFor()
      await page.reload({ waitUntil: 'load' })
      await page.getByRole('button', { name: 'Settings', exact: true }).waitFor()
      const toggleAfterReload = page.getByRole('button', { name: /^(Open|Collapse) sidebar$/ })
      await expect.poll(() => toggleAfterReload.getAttribute('aria-keyshortcuts'))
        .toBe(modifier === 'Meta' ? 'Shift+Meta+.' : 'Control+Shift+.')
      const wasOpen = await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).isVisible()
      await page.keyboard.press(sidebarKey)
      await page.getByRole('button', { name: wasOpen ? 'Open sidebar' : 'Collapse sidebar', exact: true }).waitFor()
      // The rail toggle moves during collapse; reopen with the binding this case exercises.
      if (wasOpen) await page.keyboard.press(sidebarKey)
      await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).waitFor()
      await open()
      await page.getByRole('button', { name: 'Edit shortcut for Toggle left sidebar', exact: true }).click()
      await editor.getByRole('button', { name: 'Press a shortcut', exact: true }).focus()
      const other = await context.newPage()
      await other.goto(scaffold.authenticatedUrl, { waitUntil: 'load' })
      await other.getByRole('button', { name: 'Settings', exact: true }).waitFor()
      await other.keyboard.press(referenceKey)
      await other.getByRole('button', { name: 'Edit shortcut for Toggle left sidebar', exact: true }).click()
      await other.getByRole('button', { name: 'Remove', exact: true }).click()
      await editor.getByText('Shortcut configuration or available commands changed. Review the latest bindings before saving.', { exact: true }).waitFor()
      await page.bringToFront()
      await editor.getByRole('button', { name: 'Press a shortcut', exact: true }).focus()
      await page.keyboard.press(`${modifier}+Shift+,`)
      expect(await editor.getByRole('button', { name: 'Retry save', exact: true }).count()).toBe(0)
      await compareOrRefreshGolden(join(expected, 'edit-stale.expected.md'),
        await captureStableAria(page, '[data-shortcut-modal="shortcut-edit"]', scaffold.workspaceCwd), mode)
      await editor.getByRole('button', { name: 'I have reviewed the latest configuration', exact: true }).click()
      await editor.getByRole('button', { name: 'Retry save', exact: true }).click()
      await editor.waitFor({ state: 'hidden' })
      await page.getByRole('button', { name: 'Edit shortcut for Toggle left sidebar', exact: true }).click()
      await editor.getByRole('button', { name: 'Restore default', exact: true }).click()
      await editor.waitFor({ state: 'hidden' })
      await page.keyboard.press('Escape')
      expect(await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).getAttribute('aria-keyshortcuts'))
        .toBe(defaultBinding)
      const stored = await page.evaluate((): unknown => JSON.parse(localStorage.getItem('dsh.keybindings.v1')!))
      const profile = platform === 'MacIntel' ? 'macos' : platform === 'Win32' ? 'windows' : 'linux'
      expect(stored).toEqual({ schemaVersion: 1, profiles: { [`web:${profile}`]: {} } })
    } finally { await context.close() }
  })

})
