"""Count changed old production lines by merge-base blame commit; never execute PR files."""

import argparse
from collections import Counter
import json
import os
from pathlib import PurePosixPath
import re
import subprocess

from pygments import lex
from pygments.lexers import get_lexer_for_filename
from pygments.token import Comment, Literal


EXCLUDED = frozenset((
    'vendor', 'node_modules', 'dist', 'lib', 'build', 'coverage', 'target',
    'test', 'tests', '__tests__', 'fixture', 'fixtures', 'snapshot', 'snapshots',
    'testing', 'test-support', 'support', 'examples', 'docs', 'gen', 'generated', 'generated-effect',
))
EXTENSIONS = frozenset(('.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.css', '.scss', '.py', '.c', '.h', '.cpp', '.hpp', '.rs', '.html'))
SHIPPED_ROOTS = ('apps/desktop/renderer/', 'packages/experimental/code-runtime-python/py/')
SHIPPED_FILES = frozenset(('python/sdk-runtime/runtime-bootstrap.mjs', 'packages/experimental/webworker-packer/bin.js'))
GENERATED = re.compile(r'auto-generated|automatically generated|generated by|do not edit', re.I)
SHA = re.compile(r'[0-9a-f]{40}')


def git(repo, *args):
    """Run a bounded read-only Git command without external diff drivers or replacements."""
    return subprocess.run(
        ['git', '-C', repo, '--no-replace-objects', *args], check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120,
        env={**os.environ, 'GIT_TERMINAL_PROMPT': '0'},
    ).stdout


def production_path(path):
    """Recognize shipped source roots, excluding tests, generated files and tooling."""
    name = PurePosixPath(path)
    shipped = (name.parts[0] in ('packages', 'apps', 'python', 'native') and 'src' in name.parts) \
        or path.startswith(SHIPPED_ROOTS) or path in SHIPPED_FILES
    return (
        shipped
        and not EXCLUDED.intersection(name.parts)
        and not re.search(r'\.(?:test|spec|e2e|gen|generated|d)\.', name.name)
        and name.stem != 'testing'
        and name.suffix in EXTENSIONS
    )


def code_lines(path, source):
    """Return physical lines containing non-comment, nonblank tokens, including mixed lines."""
    lexer = get_lexer_for_filename(path, stripnl=False, ensurenl=False)
    lines = set()
    line = 1
    leading = True
    for kind, value in lex(source, lexer):
        if leading and (kind in Comment or kind in Literal.String.Doc):
            if GENERATED.search(value):
                return set()
        elif value.strip():
            leading = False
        for index, fragment in enumerate(value.split('\n')):
            if index:
                line += 1
            if (kind not in Comment or kind in Comment.Preproc or kind in Comment.PreprocFile) \
                    and kind not in Literal.String.Doc and fragment.strip():
                lines.add(line)
    return lines


def changed_files(repo, base, head):
    """Yield old paths and blob IDs, preserving rename detection and arbitrary filenames."""
    fields = git(repo, 'diff', '--raw', '-z', '--no-abbrev', '--find-renames',
                 '--no-ext-diff', '--no-textconv', base, head, '--').split(b'\0')
    index = 0
    while index < len(fields) - 1:
        metadata = fields[index].decode('ascii').split()
        path = os.fsdecode(fields[index + 1])
        index += 2
        if metadata[4].startswith(('R', 'C')):
            index += 1
        if metadata[0] not in (':100644', ':100755') or not production_path(path):
            continue
        if metadata[2] != metadata[3]:
            yield path, metadata[2], metadata[3]


def measure(repo, base, head):
    """Compute the merge base and attribute changed old code lines to their last commits."""
    for revision in (base, head):
        if not SHA.fullmatch(revision):
            raise ValueError('base and head must be full commit SHAs')
    if git(repo, 'rev-parse', '--is-shallow-repository').strip() != b'false':
        raise ValueError('blame requires complete history')
    merge_base = git(repo, 'merge-base', base, head).decode().strip()
    counts = Counter()
    files = 0
    for path, old_blob, new_blob in changed_files(repo, merge_base, head):
        source = git(repo, 'cat-file', 'blob', old_blob).decode('utf-8', errors='replace')
        eligible = code_lines(path, source)
        if not eligible:
            continue
        if new_blob == '0' * 40:
            changed = eligible
        else:
            patch = git(repo, 'diff', '--no-ext-diff', '--no-textconv', '--text', '--unified=0',
                        old_blob, new_blob, '--').decode('utf-8', errors='replace')
            changed = set()
            for start, length in re.findall(r'^@@ -(\d+)(?:,(\d+))? \+\d+(?:,\d+)? @@', patch, re.M):
                start = int(start)
                changed.update(eligible.intersection(range(start, start + int(length or '1'))))
        if not changed:
            continue
        files += 1
        # One blame per file covers all changed ranges; unchanged intervening lines never count.
        blame = git(repo, 'blame', '--no-textconv', '--line-porcelain', '-L', f'{min(changed)},{max(changed)}',
                    merge_base, '--', path).decode('utf-8', errors='replace')
        attributed = 0
        for commit, line in re.findall(r'^([0-9a-f]{40}) \d+ (\d+)(?: \d+)?$', blame, re.M):
            if int(line) in changed:
                counts[commit] += 1
                attributed += 1
        if attributed != len(changed):
            raise ValueError(f'incomplete blame for {path!r}')
    return {'mergeBase': merge_base, 'files': files, 'totalLines': sum(counts.values()), 'commitLines': dict(counts)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('base')
    parser.add_argument('head')
    parser.add_argument('--repo', default='.')
    args = parser.parse_args()
    print(json.dumps(measure(args.repo, args.base, args.head)))
